name: Pre-merge Checks
'on':
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Use the appropriate Node.js version
      - run: npm install --legacy-peer-deps
      - run: npm install -g expo-cli # Install expo-cli globally
      - run: npx expo export:web # Use npx to run expo commands
      - run: npm test # Run your tests here